USE [master]
GO

/****** Object:  Database [PIZZARIA_UDS]    Script Date: 07/04/2019 21:15:09 ******/
CREATE DATABASE [PIZZARIA_UDS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PIZZARIA_UDS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PIZZARIA_UDS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PIZZARIA_UDS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PIZZARIA_UDS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [PIZZARIA_UDS] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PIZZARIA_UDS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PIZZARIA_UDS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PIZZARIA_UDS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PIZZARIA_UDS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PIZZARIA_UDS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PIZZARIA_UDS] SET ARITHABORT OFF 
GO

ALTER DATABASE [PIZZARIA_UDS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PIZZARIA_UDS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PIZZARIA_UDS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PIZZARIA_UDS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PIZZARIA_UDS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PIZZARIA_UDS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PIZZARIA_UDS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PIZZARIA_UDS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PIZZARIA_UDS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PIZZARIA_UDS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PIZZARIA_UDS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PIZZARIA_UDS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PIZZARIA_UDS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PIZZARIA_UDS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PIZZARIA_UDS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PIZZARIA_UDS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PIZZARIA_UDS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PIZZARIA_UDS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PIZZARIA_UDS] SET  MULTI_USER 
GO

ALTER DATABASE [PIZZARIA_UDS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PIZZARIA_UDS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PIZZARIA_UDS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PIZZARIA_UDS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PIZZARIA_UDS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PIZZARIA_UDS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PIZZARIA_UDS] SET  READ_WRITE 
GO

CREATE LOGIN uds_user WITH PASSWORD='dba_uds', DEFAULT_DATABASE=[PIZZARIA_UDS], DEFAULT_LANGUAGE=[Português (Brasil)]
GO

USE [PIZZARIA_UDS]
GO

CREATE USER uds_user FOR LOGIN uds_user
GO

ALTER ROLE db_owner ADD MEMBER uds_user;
GO

ALTER ROLE db_datareader ADD MEMBER uds_user;
GO

ALTER ROLE db_datawriter ADD MEMBER uds_user;
GO


/****** Object:  Table [dbo].[PEDIDOS]    Script Date: 07/04/2019 21:16:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PEDIDOS](
	[ID_PEDIDO] [int] IDENTITY(1,1) NOT NULL,
	[TAMANHO] [int] NULL,
	[SABOR] [int] NULL,
	[VALOR_FINAL] [float] NULL,
	[TEMPO_PREPARO] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_PEDIDO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[PEDIDO_PERSONALIZACAO]    Script Date: 07/04/2019 21:16:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PEDIDO_PERSONALIZACAO](
	[ID_PEDIDO] [int] NULL,
	[PERSONALIZACAO] [int] NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PEDIDO_PERSONALIZACAO]  WITH CHECK ADD FOREIGN KEY([ID_PEDIDO])
REFERENCES [dbo].[PEDIDOS] ([ID_PEDIDO])
GO


/****** Object:  View [dbo].[V_PERSONALIZACOES]    Script Date: 07/04/2019 21:16:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[V_PERSONALIZACOES]
AS

SELECT 1 AS ID, 'Extra Bacon' AS DESCRICAO, 3.0 AS VALOR, 0 AS TEMPO
UNION
SELECT 2, 'Sem Cebola', 0, 0
UNION
SELECT 3, 'Borda Recheada', 5.0, 5

GO


/****** Object:  View [dbo].[V_SABORES]    Script Date: 07/04/2019 21:17:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE VIEW [dbo].[V_SABORES]
AS

SELECT 1 AS ID, 'Calabresa' AS DESCRICAO, 0 AS TEMPO
UNION
SELECT 2, 'Marguerita', 0 AS TEMPO
UNION
SELECT 3, 'Portuguesa', 5 AS TEMPO

GO


/****** Object:  View [dbo].[V_TAMANHOS]    Script Date: 07/04/2019 21:17:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[V_TAMANHOS] 
AS

SELECT 1 AS ID, 'Pequena' AS DESCRICAO, 20.0 AS VALOR, 15 AS TEMPO
UNION
SELECT 2, 'Média', 30.0, 20
UNION
SELECT 3, 'Grande', 40.0, 25

GO






